/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/my_animated_cheetah.glb
Author: dinomaster (https://sketchfab.com/dinomaster)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/my-animated-cheetah-b8d48489de28454fbf400dd1017067f1
Title: my animated cheetah
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations, Environment, Sparkles } from '@react-three/drei'
import { Canvas } from 'react-three-fiber'
import { OrbitControls } from '@react-three/drei'
import { useEffect } from 'react'
import { Color } from 'three'

const Model = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/my_animated_cheetah.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect (() => {

    actions[names[0]].reset().fadeIn(0.5).play()
  }, [actions, names])

  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.58}>
          <group name="cheetah_runfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Cheetah" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Cheetah(0)">
                    <group name="Bip01" position={[0, 0, 69.55]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                      <group name="Object_7">
                        <primitive object={nodes._rootJoint} />
                        <group name="Object_64" position={[0, 0.08, -6.23]} rotation={[-Math.PI / 2, 0, 0]} />
                        <skinnedMesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.Cheetah_Default} skeleton={nodes.Object_65.skeleton} castShadow />
                      </group>
                    </group>
                    <group name="Cheetah(1)" position={[0, 6.23, 0.08]} />
                  </group> 
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>

   

  )
}


useGLTF.preload('/my_animated_cheetah.glb')

const Cheetah = (props) => {
  return (
    <Canvas camera={{ position: [2, 2, 2], fov: 50 }} shadows >
      <Environment preset="city" background />
      <OrbitControls />
     
      <ambientLight intensity={0.5}  />
      <directionalLight position={[10, 10, 5]} intensity={1.5} />
      <spotLight position={[1000, 0, 0]} angle={0.15} penumbra={1} intensity={2} castShadow />
      <pointLight position={[-1000, 0, -2000]} intensity={1.5} />
      <pointLight position={[0, -1000, 0]} intensity={1.5} />
      <fog attach="fog" args={['white', 5, 15]} />
      <group position={[0,-1,0]}>
      
      <mesh receiveShadow rotation={[-Math.PI / 2, 0, 0]} position={[0, -3, 0]} >
        
        <shadowMaterial attach="material" opacity={0.3} />
      </mesh>
      
      <mesh receiveShadow rotation={[-Math.PI / 2, 0, 0]} position={[0, -3, 0]} >
        
        <meshStandardMaterial attach="material" color="white" />
      </mesh>
</group>
      <Model {...props} />
    </Canvas>
  )
}

export default Cheetah

